# This file controls what config variables you want to be able to allow your users
# to set, as well as those you'll be able to access from within the application.
# 
# If you want to be able to access a string config[:site_title], for example:
#   
# site_title:
#   name: Site Title
#   type: string
#   default: My Site
#   
# 'name' is the name that appears in the edit form
# 
# 'type' can be 'string' for a text field, 'password' for a password field or 'text' for a text area
#   'type' defaults to 'string'
# 
# 'default' is the default value to use if there's no entry in the database. Otherwise, nil will be returned
# 
# Some Examples:
#   
# site_title:
#   name: Site Title
#   default: My Site
#   type: string
#   
# site_description:
#   name: Description for Google
#   default: Lots of Awesomeness Here
#   type: text
# Catalogo de iniciativas, Catalogo de representantes, registro de usuarios, notificaciones, catalogo de comisiones  
# secret:
#   name: Secret Password for Accessing Secret Areas
#   default: secret
#   type: password

initiatives:
  name: Catalogo de Iniciativas
  type: boolean
  default: true

representatives: 
  name: Catalogo de representantes
  type: boolean
  default: true

users: 
  name: Registro de Usuario
  type: boolean
  default: true

notifications:
  name: Notificaciones
  type: boolean
  default: true

commissions: 
  name: Catalogo de comisiones
  type: boolean
  default: true
  
  