production:
  solr:
    hostname: 108.59.252.197
    port: 8180
    path: /solr/curul
    log_level: WARNING

development:
  solr:
    hostname: 127.0.0.1
    port: 8180
    path: /solr
    log_level: INFO

test:
  solr:
    hostname: 127.0.0.1
    port: 8180
    path: /solr
    log_level: WARNING