production:
  solr:
    hostname: 50.57.172.178
    port: 8080
    path: /solr/curul
    log_level: WARNING

development:
  solr:
    hostname: 50.57.172.178
    port: 8080
    path: /solr/curul
    log_level: INFO

test:
  solr:
    hostname: 127.0.0.1
    port: 8180
    path: /solr
    log_level: WARNING